# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fb17bc51c0c55e0387e49182f44289b23dbb30247b45e5bcd4169ac4c281a1517bd19a53d02a1d120794d1fd3558113d65c1a00aab3230d60ca6470f58fcee6

test:
  secret_key_base: 2498e768af450e2ce0f368a9f49c1aadcdea15c1f18adf9c85c9400940db1f9eecbe8537f39baac06e46935a08277422f9e482041d9a5d2968e3428ed023e116

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
